version: '3.7'
services:
  mysql:
    image: ghcr.io/deltasystems/docker-development-environemtns/lamp-8-mysql:latest
    ports:
      - "3307:3306"
    #volumes:
    #  - "./build-dev/conf/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf"
    #  - "./build-dev/mysql-on-build:/docker-entrypoint-initdb.d"
  web:
    image: ghcr.io/deltasystems/docker-development-environemtns/lamp-8-web:latest
    ports:
      - "8081:80"
    volumes:
      - "./src:/var/www/vhosts/myvhost"
      #- "./deploy.php:/var/www/vhosts/myvhost/private/deploy.php"
      #- "./deployer.phar:/var/www/vhosts/myvhost/private/deployer.phar"
      #- "./build-dev/conf/supervisor:/etc/supervisor/conf.d"
    links:
      - 'mysql:mysql'
