version: '3.7'
services:
  mysql:
    image: ghcr.io/deltasystems/docker-development-environments/wordpress-mysql:latest
    ports:
      - "3307:3306"
    #volumes:
      #- "./conf/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      #- "./mysql-on-init:/docker-entrypoint-initdb.d"
  web:
    image: ghcr.io/deltasystems/docker-development-environments/wordpress-web:latest
    ports:
      - "8081:80"
    volumes:
      #- "./conf/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini"
      - "./src:/var/www/vhosts/myvhost"
      #- "./deploy.php:/var/www/vhosts/myvhost/private/deploy.php"
      #- "./deployer.phar:/var/www/vhosts/myvhost/private/deployer.phar"
    links:
      - 'mysql:mysql'
